name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        if [ "${{ matrix.python-version }}" = "3.9" ]; then
          python -m pip install -r requirements_39.txt
        elif [ "${{ matrix.python-version }}" = "3.10" ]; then
          python -m pip install -r requirements_310.txt
        elif [ "${{ matrix.python-version }}" = "3.11" ]; then
          python -m pip install -r requirements_311.txt
        fi
        python -m pip install -e .
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Add any necessary system dependencies here
        # For example: sudo apt-get install -y libhdf5-dev

    - name: Test with pytest
      run: |
        pytest --cov=micaflow tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false